---
- name: Docker install in container
  hosts: Myservers
  remote_user: ec2-user
  become: true

  tasks:
    - name: Install Docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 
    
    - name: Modify Repo string
      replace: 
        path: /etc/yum.repos.d/docker-ce.repo
        regexp: '[$]releasever'
        replace: "7"
    
    - name: Add repository
      yum:
        name: 
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
       # description: EPEL YUM repo
        #baseurl: https://download.fedoraproject.org/pub/epel/7/$basearch/
        state: present


    # Handler showing how to clean yum metadata cache
    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: no

    - name: Install Docker package
      yum:
        name:
          - http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
          - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
          - http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm
          - http://mirror.centos.org/centos/7/extras/x86_64/Packages/slirp4netns-0.4.3-4.el7_8.x86_64.rpm
          - https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/f/fuse3-libs-3.6.1-2.el7.x86_64.rpm
          - docker-ce
          - docker-ce-cli
          - python-pip
        state: present
    
    - name: Make sure docker service is running
      ansible.builtin.systemd:
        state: started
        name: docker

    - name: Run Container 
      pip:
        name: docker
    
    - name: Pull default Docker image
      docker_image: 
        name: httpd

    - name: Create container httpd
      docker_container:
        name: MyWebServer
        state: started
        image: httpd:latest
        detach: yes
        ports:
          - "8080:80"
      tags: startcontainer

